### ISSUE TITLE
Not working in a screen session

### ISSUE THREAD

**Issue by thesushantpatil** [alvinj/Teleport#2]
Alex,

Teleport works on my end smoothly otherwise. But once I initiate a screen session, it is dysfunctional (bash: tp: command not found). Is there any way around this? 

Thanks,

Sushant

**Comment by alvinj** [comment]
Hi Sushant,

I don’t know what you mean by a screen session, but the important thing is that the Teleport setup files are read whenever a new terminal is created.

For instance, on MacOS, when I open a new Terminal window or tab, I know that the *.bash_profile* file is read, so I put the Teleport setup/configuration in that file. I haven’t looked at this in a while, but it looks like other files that may be read when a new terminal session is started are:

~/.bash_login
~/.profile
~/.bashrc

I found that at [this gnu.org page](https://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html).

So I think the solution is to determine which file(s) are read when a new screen session is started, and put the Teleport configuration in that file.

I hope that helps, and best wishes,
Al

**Comment by thesushantpatil** [comment]
Thanks. The trick that worked for me is putting Teleport setup/configuration in .bashrc, instead of .bash_profile.

**Comment by alvinj** [comment]
That’s great to hear — I’m glad it’s working!
