### ISSUE TITLE
Only last path is writen to $TP_HISTORY_FILE

### ISSUE THREAD

**Issue by iFreilicht** [alvinj/Teleport#3]
I'm really at a loss. I love this tool, and I'm very certain that I've used it or something similar a few years ago, but I now installed it on a new machine and the whole history part of it seems to be broken.

I can use `tp` to change directories, but only the current directory is writen to the history file. I tested in both bash and zsh, both behave the same, except that for zsh I had to add `typeset -A dirlist` at the top of `function tp ()` to get rid of this error:

    i_load_dirlist:6: dirlist: assignment to invalid subscript range

No big deal, I guess zsh just doesn't like implicit declaration of arrays. 
But look at this:
```~ $ cat $TP_HISTORY_FILE
/home/felix
/home/felix/.config
/home/felix/.dotfiles
~ $ cd Documents
…/Documents $ cat $TP_HISTORY_FILE
/home/felix/Documents

```
Note there is now a newline at the end.
It seems like `dirlist` and `listsize` are out of scope inside `i_addToHistory()`.

**Comment by iFreilicht** [comment]
Ah nevermind, the tool I used was [autojump](https://github.com/wting/autojump).

**Comment by alvinj** [comment]
That’s great, I’m glad you figured it out!
